name: "Build 3ml"


on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - '*.md'
      - '*.txt'
      - '*.json'
      - '*.yml'
      - '*.yaml'
      - 'examples/**'
      - 'scripts/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - '*.md'
      - '*.txt'
      - '*.json'
      - '*.yml'
      - '*.yaml'
      - 'examples/**'
      - 'scripts/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    # Setup go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '1.23.9'

      - name: Install dependencies
        run: go mod download

      - name: Build 3ml
        run: go build -o 3ml .

  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      actions: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '1.23.9'
      
      - name: Run tests
        run: go test -v ./... -coverprofile=coverage.txt
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.txt
